name: Run Spring Boot Tests with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for testing
        run: |
          cd server
          docker build -t auth-service-test .

      - name: Run tests in Docker container
        run: |
          cd server
          docker run --name test-container auth-service-test ./mvnw clean test

      - name: Copy test results from container
        if: always()
        run: |
          cd server
          # Copy test results from the container
          docker cp test-container:/app/target ./target || echo "No target directory found"
          # Clean up the container
          docker rm test-container || true

      - name: List test results (for debugging)
        if: always()
        run: |
          cd server
          find . -name "*.xml" -path "*/surefire-reports/*" || echo "No test result files found"
          ls -la target/surefire-reports/ || echo "No surefire-reports directory"

      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: server/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: server/target/surefire-reports/
          if-no-files-found: warn
